### ISSUE TITLE
White 2 (US) not launching after exporting

### ISSUE THREAD

**Issue by HandsomeKeks** [kingdom-of-ds-hacking/CTRMap-CE#3] opened 2023-02-18 13:47 UTC
After exporting a Gen5 (i tested it with B2 and W2 both US versions) it doesn't launch like expected but is stuck in a white screen, also the dsi binaries are not working anymore after exporting.

**Comment by HelloOO7** [comment] 2023-02-18 14:10
DSi features being removed when exporting is intended behavior. You have to run the ROMs in NDS mode to ensure they work properly.

Can you identify the earliest release in which this issue is present?

**Comment by HandsomeKeks** [comment] 2023-02-18 14:54
https://github.com/kingdom-of-ds-hacking/CTRMap-CE/releases/tag/2023%2F01%2F20%2F1
this one doesn't work for me, the one before does

**Comment by HelloOO7** [comment] 2023-02-18 15:06
Can you try with #[03ad53c](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/commit/03ad53cb86d7641191ccd46ba910f687d9d8b84e)?

**Comment by HandsomeKeks** [comment] 2023-02-18 15:23
can you build it and put it into the release ? idk how to build it

**Comment by HelloOO7** [comment] 2023-02-18 15:47
I'm not going to make a release if I know there is possibly an issue with the changes. Make a recursive clone of the repo and then build it in NetBeans.

**Comment by HandsomeKeks** [comment] 2023-02-19 11:43
okay when i try to build it with NetBeans i get 22 errors
[build.txt](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/files/10776751/build.txt)

**Comment by HelloOO7** [comment] 2023-02-19 16:00
That one's on me, seems like I forgot to run `git submodule update` when pushing. Try with #[69d8835](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/commit/69d883556516f3dffed9f668272847c83dbc0021) and make sure that the recursively included submodules are re-cloned as well.

**Comment by HandsomeKeks** [comment] 2023-02-19 19:22
[build.txt](https://github.com/kingdom-of-ds-hacking/CTRMap-CE/files/10777712/build.txt)
got some more errors now

**Comment by HelloOO7** [comment] 2023-02-19 19:32
You didn't link the JOGL and submodule dependencies properly. Resolve the link problems and these errors should disappear.

**Comment by HelloOO7** [comment] 2023-04-09 22:03
Fixed in 2023/04/10/1.

**Closed by HelloOO7** 2023-04-09 22:03 UTC
